# Generated by Django 3.2.5 on 2022-03-28 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20220328_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_css',
            field=models.CharField(max_length=200, null=True, verbose_name='CSS Класс'),
        ),
        migrations.AlterField(
            model_name='cmsslider',
            name='cms_img',
            field=models.ImageField(upload_to='slider_img/'),
        ),
    ]
